service: blog
provider:
  name: aws
  runtime: python2.7
  memorySize: 512
  environment:
    STATUS: ${file(env.yml):STATUS}
  iamRoleStatements:
      -  Effect: "Allow"
         Action:
           - "dynamodb:*"
         Resource:
           - "arn:aws:dynamodb:eu-west-2:298879669036:table/MyGlobalTable"
           - "arn:aws:dynamodb:us-east-1:298879669036:table/MyGlobalTable"
      -  Effect: "Allow"
         Action:
           - "logs:CreateLogGroup"
           - "logs:CreateLogStream"
           - "logs:PutLogEvents"
           - "xray:PutTraceSegments"
           - "xray:PutTelemetryRecords"
         Resource:
           - "*"

package:
  include:
    - vendored/**
  exclude:
    - .git/**

functions:
  get_item:
    handler: get.get_item
    events:
      - http:
          path: get/{item_id}
          method: GET
          cors: true

  create_item:
    handler: post.create_item
    events:
      - http:
          path: create
          method: POST
          cors: true

  get_health:
    handler: health.lambda_handler
    events:
      - http:
          path: health
          method: GET
          cors: true