service: Recipe
custom:
  customDomain:
    domainName: globe.easypeasyrecipe.co.uk
    basePath: ''
    stage: dev
    createRoute53Record: true
provider:
  name: aws
  runtime: python2.7
  memorySize: 512
  environment:
    STATUS: ${file(env.yml):STATUS}
  iamRoleStatements:
      -  Effect: "Allow"
         Action:
           - "dynamodb:*"
         Resource:
           - "arn:aws:dynamodb:eu-west-2:298879669036:table/RecipeTable"
           - "arn:aws:dynamodb:eu-central-1:298879669036:table/RecipeTable"
      -  Effect: "Allow"
         Action:
           - "logs:CreateLogGroup"
           - "logs:CreateLogStream"
           - "logs:PutLogEvents"
           - "xray:PutTraceSegments"
           - "xray:PutTelemetryRecords"
         Resource:
           - "*"

package:
  include:
    - vendored/**
  exclude:
    - .git/**

functions:
  no-op:
    name: NoOp
    handler: hello.noop
    events:
      - http: POST noOp
      
  create_recipe:
    handler: addRecipe.create_recipe
    events:
      - http:
          path: create
          method: POST
          cors: true

  get_recipe:
    handler: getRecipe.get_recipe
    events:
      - http:
          path: get/{RecipeName}
          method: GET
          cors: true

  get_health:
    handler: health.lambda_handler
    events:
      - http:
          path: health
          method: GET
          cors: true
